name: AI Triage

on:
  issues:
    types: [opened, labeled]

jobs:
  triage:
    runs-on: ubuntu-latest

    if: |
      (
        github.event.action == 'opened' &&
        contains(toJson(github.event.issue.labels), 'bug auto triage')
      )
      ||
      (
        github.event.action == 'labeled' &&
        github.event.label.name == 'bug auto triage'
      )
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: AI Triage
        id: ai-triage
        run: |
          node .github/scripts/triage-ai.js > ai_output.txt
          echo "commentBody<<EOF" >> $GITHUB_OUTPUT
          cat ai_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Comment
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.ai-triage.outputs.commentBody }}
