name: AI Triage

on:
  issues:
    types: [opened, labeled]

jobs:
  triage:
    runs-on: ubuntu-latest

    if: |
      (
        github.event.action == 'opened' &&
        contains(toJson(github.event.issue.labels), 'bug auto triage')
      )
      ||
      (
        github.event.action == 'labeled' &&
        github.event.label.name == 'bug auto triage'
      )
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install openai@3.2.1

      - name: AI Triage
        run: node scripts/triage-ai.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}

      - name: Create Comment
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.ai-triage-parse.outputs.commentBody }}